enthought/okonomiyaki

- okonomiyaki/platforms/__init__.py
- okonomiyaki/platforms/platform.py
- okonomiyaki/platforms/platform_filters.py
- okonomiyaki/platforms/tests/test_epd_platform.py
- okonomiyaki/platforms/tests/test_platform.py
- okonomiyaki/platforms/tests/test_platform_filters.py
- okonomiyaki/repositories/grits.py
This adds code so that we can easily filter on platforms using the pisi legacy (e.g. `platforms=all`, or `platforms=!win`) in a way that is "typed" and amenable to additional platforms
> Add platform filtering

- okonomiyaki/file_formats/_package_info.py
- okonomiyaki/file_formats/tests/test__package_info.py
Parsing a `PKG-INFO` was causing `KeyError` exceptions for unsupported versions.
> BUG: fix handling of unsupported metadata version.

- okonomiyaki/file_formats/_egg_info.py
- okonomiyaki/file_formats/tests/test_egg_file_format.py
- okonomiyaki/platforms/platform.py
Add a `platform_tag` to `EggMetadata`.
Some potential design issues:
* how/where to handle the conversion between `None` and the string representation as per pep425. We could add an `pep425_tag` property that would do the conversion
* there may be a source of confusion between `platform` (an object representing the platform) and `platform_tag`.
@sjagoe
> Add platform tag

- okonomiyaki/errors.py
- okonomiyaki/file_formats/__init__.py
- okonomiyaki/file_formats/_egg_info.py
- okonomiyaki/file_formats/tests/test_egg_file_format.py
- okonomiyaki/repositories/enpkg.py
* rename `Dependency` to the better `Requirement`
* use `Requirement` in `EggMetadata` instead of strings.
@sjagoe
> Use objects for dependencies

- okonomiyaki/platforms/epd_platform.py
- okonomiyaki/platforms/tests/test_epd_platform.py
Add a `from_running_python` to `EPDPlatform`, using the architecture of the running python process to determine the architecture (e.g. 64 bits for 64 bits python even if the underlying machine/kernel is 32 bits)
@sjagoe
> ENH: add EPDPlatform.from_running_python.

- okonomiyaki/errors.py
- okonomiyaki/file_formats/_egg_info.py
- okonomiyaki/file_formats/tests/test_egg_file_format.py
@sjagoe 
I decided against support `py3` as we may want to support `3.4` (brood) and `3.5` (now in beta) when supporting python 3. Hopefully at that point we will be in position to update to a new metadata format `2.0`.
> Add major only python tag support

- okonomiyaki/file_formats/_egg_info.py
- okonomiyaki/file_formats/egg.py
- okonomiyaki/file_formats/tests/test_egg_file_format.py
> BUG: fix unicode handling in PKG-INFO and metadata summary.

- okonomiyaki/file_formats/__init__.py
- okonomiyaki/file_formats/_egg_info.py
- okonomiyaki/file_formats/pep425.py
- okonomiyaki/file_formats/setuptools_egg.py
- okonomiyaki/file_formats/tests/test__egg_info.py
- okonomiyaki/file_formats/tests/test_pep425.py
Use a proper object `PythonImplementation` to represent python tags instead of strings.
Backward compatibility is almost kept by automatically converting string to `PythonImplementation` instances in `EggMetadata` constructor (I changed the argument name to `EggMetadata.__init__` from `python_tag` to `python` for consistency's sake though).
@sjagoe
> Unstringify python tag

- CHANGELOG
- okonomiyaki/file_formats/setuptools_egg.py
- okonomiyaki/file_formats/tests/test_setuptools_file_format.py
This is the first step to fix ABI tag handling in enstaller `repack`: adds abi tag guessing for common cases and legacy cases.
@sjagoe
> ENH: add abi tag guessing for SetuptoolsMetadata.from_egg.

- okonomiyaki/platforms/epd_platform.py
- okonomiyaki/platforms/tests/test_epd_platform.py
Add support for epd string like `rh5-amd64` or `rh5-x86_64`.
@sjagoe
> ENH: automatically convert arch string in EPDPlatform.from_epd_string.

- okonomiyaki/file_formats/_blacklist/__init__.py
- okonomiyaki/file_formats/_blacklist/pkg_info_data.py
- okonomiyaki/file_formats/_egg_info.py
- okonomiyaki/file_formats/_package_info.py
- okonomiyaki/file_formats/tests/common.py
- okonomiyaki/file_formats/tests/test__egg_info.py
- okonomiyaki/file_formats/tests/test__package_info.py
This PR:
* adds private APIs to `PackageInfo`, `LegacySpecDepend` and `EggMetadata` to build the corresponding objects from an egg + a pre-computed sha256
* use those APIs internally to avoid computing sha256 multiple times for an egg
* the public APIs `*.from_egg` only compute the checksum when it may be required, so that most eggs don't need any sha256 computation at all if given a path
It also enforces `PackageInfo.from_string` to take a unicode string.
@sjagoe
> Avoid sha256 calculation blacklist

- CHANGELOG
- okonomiyaki/versions/__init__.py
- okonomiyaki/versions/semver.py
- okonomiyaki/versions/tests/test_semver.py
Cleaned up version of #105 
Looking at https://github.com/rbarrois/python-semanticversion, its comparison algo is almost one order of magnitude slower than our implementation (because it does int/string conversion at every step).
@sjagoe
> Add semver v2

- okonomiyaki/runtimes/runtime.py
- okonomiyaki/runtimes/tests/test_runtime.py
- tox.ini
add a `Runtime` and `PythonRuntime` classes.
Those do not really belong in okonomiyaki (not really metadata), but they need to be used in both enstaller and jaguar, so will stay there until jaguar and enstaller are merged.
> Add runtime

- CHANGELOG
- okonomiyaki/versions/__init__.py
- okonomiyaki/versions/pep440.py
- okonomiyaki/versions/tests/test_pep440.py
Implements the basic parts PEP440. It is not complete as it does not implement the replacements, but since those are not implemented in pip either, I don't think it is a big deal for now.
We don't use distlib's version as our version is ~50 % faster (we don't parse the string twice !). I also believe our implementation is simpler.
@jvkersch
> Add pep440

- okonomiyaki/file_formats/egg.py
- okonomiyaki/file_formats/tests/test_egg_file_format.py
The accept function in `EggRewriter` is now taking two arguments, to allow taking decision on the existing content.
> ENH: accept now get nameset.

- .travis.yml
- okonomiyaki/errors.py
- okonomiyaki/file_formats/_egg_info.py
- okonomiyaki/file_formats/tests/test__egg_info.py
- okonomiyaki/platforms/abi.py
- okonomiyaki/platforms/tests/test_abi.py
- okonomiyaki/runtimes/runtime_info.py
- okonomiyaki/runtimes/runtime_metadata.py
- tox.ini
This PR does the following:
* change `UnsupportedMetadata` exception to store `metadata_version` 
* reject incompatible `metadata_version` when reading/writing egg metadata. When reading, is considered as invalid an unsupported major metadata version. When writing, any metadata version not fully supported is rejected (to avoid data loss).
* `EggMetadata.is_strictly_supported` property is False when an unsupported but backward compatible metadata_version is detected (e.g. `1.5` metadata_version w/ okonomiyaki only supporting up to `1.3`)
* Add support for 3.5 in CI
@sjagoe
> Handle unsupported metadata

- okonomiyaki/file_formats/_egg_info.py
- okonomiyaki/file_formats/tests/test__egg_info.py
- okonomiyaki/file_formats/tests/test_egg_file_format.py
- setup.py
This adds a new field `platform_abi` in our egg metadata, thus defining a new metadata version format `1.4`.
The main rationale is to differentiate between non python packages which may have different ABIs (think Qt built w/ different versions of Visual Studio, as will be required to support python 3). For existing eggs, we can guess it from other tags (platform and python version).
@sjagoe
> Add platform abi

- okonomiyaki/file_formats/_egg_info.py
- okonomiyaki/file_formats/tests/test__egg_info.py
@sjagoe that should fix the issue you were seeing w/ `PythonDoc`.
The issue was handling eggs with the tag `py27` (I wrongly assumed we did not have any such eggs yet).
> BUG: fix platform_abi guess for pure python eggs.

- okonomiyaki/file_formats/_egg_info.py
- okonomiyaki/file_formats/_package_info.py
- okonomiyaki/file_formats/tests/test__egg_info.py
- okonomiyaki/file_formats/tests/test__package_info.py
This adds a new `EggMetadata.dump` method to write so-called metadata egg, that is egg that contain only our metadata (currently `EGG-INFO/spec/depend`, `EGG-INFO/spec/summary` and `EGG-INFO/PKG-INFO`).
The metadata are written after blacklist processing, so the metadata egg automatically gets the correct metadata.
@sjagoe
> Write metadata egg

- dev_requirements.txt
- okonomiyaki/__main__.py
- okonomiyaki/_cli/__init__.py
- okonomiyaki/_cli/tests/test_cli.py
- setup.py
Add support for `python -m okonomiyaki`. This simple CLI has 3 commands:
* spec-depend: see the `spec/depend` file (after blacklisting processing)
* summary: print the summary (in `spec/summary`)
* pkg-info: print the content of `PKG-INFO`
* show-index: print the sorted archive content
@sjagoe
> FEAT: add basic CLI for python -m okonomiyaki.

- okonomiyaki/_cli/__init__.py
I forgot that I put in an optimization to avoid computing sha256 in most cases in `EggMetadata.from_egg` ...
@sjagoe
> ENH: don't compute sha256 when not needed in okonomiyaki CLI.

- okonomiyaki/_cli/tests/test_cli.py
- okonomiyaki/file_formats/tests/test__egg_info.py
- okonomiyaki/file_formats/tests/test__package_info.py
- okonomiyaki/file_formats/tests/test_egg_file_format.py
- okonomiyaki/file_formats/tests/test_setuptools_file_format.py
- okonomiyaki/platforms/epd_platform.py
- okonomiyaki/platforms/tests/test__arch.py
- okonomiyaki/platforms/tests/test_abi.py
- okonomiyaki/platforms/tests/test_epd_platform.py
- okonomiyaki/platforms/tests/test_platform.py
- okonomiyaki/platforms/tests/test_platform_filters.py
- okonomiyaki/platforms/tests/test_python_implementation.py
- okonomiyaki/runtimes/tests/test_runtime.py
- okonomiyaki/runtimes/tests/test_runtime_info.py
- okonomiyaki/runtimes/tests/test_runtime_metadata.py
- okonomiyaki/utils/tests/test_main.py
- okonomiyaki/utils/tests/test_misc.py
- okonomiyaki/versions/tests/test_enpkg_version.py
- okonomiyaki/versions/tests/test_metadata_version.py
- okonomiyaki/versions/tests/test_pep386_workaround.py
- okonomiyaki/versions/tests/test_pep440.py
- okonomiyaki/versions/tests/test_runtime_version.py
- okonomiyaki/versions/tests/test_semver.py
Fix tests when run on recent pypy `5.x`, and also uses `unittest2` consistently for 2.6 + 2.6 fixes.
@noraderam
> Fix test new pypy

- setup.py
Also updated `zipfile2`, to get the symlink fix.
> MAINT: we rely on attr 15.2.0 (convert).

- setup.py
DEP: Add enum34 dependency for python2.7
(cherry picked from commit eb93bb8493e6007a7a5000a5efb66b5bf837298b)
> Backport the enum34 dependency addition

- okonomiyaki/file_formats/_egg_info.py
We were calling `ZipFile` 3 times, which is quite expensive for eggs with a large number of archives.
With this fix, parsing metadata of an with a large number of archives ( e.g. VTK) is only 5-10 % slower than just one call to ZipFile (compared to 200 % slower before).
Close #195
> ENH: speed-up EggMetadata parsing from egg.

- dev_requirements2.txt
- setup.py
Stevedore is only needed for testing (through haas), so we should put
the constraint for python 2.6 compatibility in dev/test requirements,
not runtime dependencies.
Fix #208
> MAINT: put stevedore version constraint in dev_requirements, where it belongs

- okonomiyaki/_cli/tests/test_cli.py
- okonomiyaki/file_formats/_egg_info.py
There are many cases where we want an EggMetadata instance for a given
egg but are not interested in the PKG-INFO content. This commit allows
EggMetadata.pkg_info to be lazily loaded.
This helps making `edm list` 30 % faster.
@johntyree
> ENH: lazily parse PKG-INFO.

- okonomiyaki/file_formats/tests/test_legacy.py
- okonomiyaki/platforms/abi.py
- okonomiyaki/platforms/python_implementation.py
This PR adds support for any (python tag, platform) pair that is present in either the eggs or egg_indices table in our instance of package.e.com. This is required for migration.
We also fix broken default ABI for cp30/cp31/cp32 on windows.
> ENH: compute default ABI for ironpython/jython.

- okonomiyaki/file_formats/tests/test__egg_info.py
- okonomiyaki/platforms/abi.py
- okonomiyaki/platforms/tests/test_abi.py
- setup.py
Closes #228 
This adds platform abi support for Python 3.6 (due to be released by the end of the year). It assumes that Visual Studio 2015 will be used (as was the case for Python 3.5). I haven't been able to find anything suggesting that this will not be the case. With Python 3.6 beta1 due out in a few weeks, such a change from msvc2015 seems unlikely.
> Add support for CPython 3.6

- okonomiyaki/file_formats/tests/test__egg_info.py
- okonomiyaki/platforms/abi.py
- okonomiyaki/platforms/tests/test_abi.py
- setup.py
How does this look @cournape? 
Add support for CPython 3.6
(cherry picked from commit 6cf78196db82c285d3d3fb7629774f0e2c5badc1)
> Backport #229 Add support for CPython 3.6

- setup.py
We fix both `author` and `author_email`. `twine` now validates email when uploading eggs/sdists, causing failures w/ our current `setup.py`.
> MAINT: fix author_* entries in setup.py.

- okonomiyaki/file_formats/egg.py
- okonomiyaki/file_formats/tests/test_egg_file_format.py
This will fix eggs built by tateru which had `PKG-INFO` to be readable by the owner only (on Unix).
> ENH: fix permissions for egg metadata written through writestr.

- okonomiyaki/file_formats/_egg_info.py
- okonomiyaki/platforms/_arch.py
- okonomiyaki/platforms/epd_platform.py
- okonomiyaki/platforms/platform.py
This is required by the new attrs 17.1.0 (see https://github.com/python-attrs/attrs/issues/191).
> MAINT: mark classes we need hashable as immutable.

- .gitignore
- okonomiyaki/platforms/_pep425_impl.py
- okonomiyaki/platforms/pep425.py
This PR update the way we call the run_pep415 script so that it can be used in frozen apps. Note that now a subprocess call will always take place.
fixes #283
> Fix/support using  run pep425 in frozen apps

- .travis.yml
- setup.py
Fixes https://github.com/enthought/okonomiyaki/issues/317
The key to this fix ended up being to add in a `pip install -U` for `attrs` into the .travis.yml. `attrs` was pre-existing in the Travis CI and the version was not recent enough.
> Remove restriction on jsonschema 3

- okonomiyaki/file_formats/tests/test__egg_info.py
- okonomiyaki/utils/test_data/__init__.py
This PR fixes the exposed tests data variables to include the new runtimes and egg that we recently added. It also fixes a bug in the eggs which was using the rh5 eggs for all platforms.
> Add missing variables for new dummy runtimes and eggs

- README.rst
fixes #378 
Update the build badge and trigger the first build on travic-ci.com (migration from travis-ci.org)
> Fix build badge to point to travis-ci.com

- okonomiyaki/runtimes/runtime_metadata.py
> Pass the runtime version to from_epd_string in _parse_from_path

- .github/workflows/test.yml
- appveyor.yml
- dev_requirements.txt
- jenkins/test
- okonomiyaki/file_formats/setuptools_egg.py
- okonomiyaki/platforms/_pep425_impl.py
- okonomiyaki/platforms/_platform.py
- okonomiyaki/platforms/tests/common.py
- okonomiyaki/platforms/tests/test_pep425.py
- okonomiyaki/runtimes/tests/test_runtime_info.py
- okonomiyaki/utils/tests/test_eggs.py
- setup.py
fixes #421 
fixes #385 
In more details
- Update the vendorized pep425 module to better support python 3.8
- Update pep425 tests to use packaging.tag to verify results
- Add testing on Python 3.8 (to verify that the pep425 changes are correct)
~- Fix relative imports. The rule of thumb is that we should not use `..` for library code and `...` for test code (it was causing issue running the tests locally from the root folder)~
- Fix _guess_platform_details function to support python 3.8 
- Update ci builds
> Fix compute abi tag

- okonomiyaki/versions/pep440.py
- okonomiyaki/versions/runtime_version.py
- okonomiyaki/versions/tests/test_pep440.py
- okonomiyaki/versions/tests/test_runtime_version.py
fixes #435 
fixes #434 
Please note that I ended up using the `from_string` function in the repr because it was the simplest way to have a string that is readable and at the same time reproduce the original object. The RuntimeVersion and PEP440Version will need to be reworked to have something more tranditional in the future
> Fix repr issues

- okonomiyaki/platforms/__init__.py
- okonomiyaki/platforms/_arch.py
- okonomiyaki/platforms/_platform.py
- okonomiyaki/platforms/abi.py
- okonomiyaki/platforms/epd_platform.py
- okonomiyaki/platforms/tests/common.py
- okonomiyaki/platforms/tests/test__arch.py
- okonomiyaki/platforms/tests/test_abi.py
- okonomiyaki/platforms/tests/test_epd_platform.py
- okonomiyaki/platforms/tests/test_platform.py
- Move the X86 and X86_64 objects to the _arch module where the belong
- Update macos version detection to detect more recent verions of macOS
- Update windows version detection to better separate between windows 10 and windows 11
- Add rh8 linux distribution support
- Add support for cp311 in EPDPlatform
- Augment and cleanup tests
> Rework and fix platform objects

- okonomiyaki/file_formats/_egg_info.py
- okonomiyaki/file_formats/tests/test__egg_info.py
Remove the use of the LegacyEPDPlatform object from the active okonomiyaki code. 
More specifically the legacy entires in the _depend_ metadata are now generated based on a single source of truth; the EPDPlatform object
> Do not use legacy epd platform

- .coveragerc
- .github/workflows/test.yml
- Generate test coverage
- Add a step to upload coverage from each job
- Add a job to collect and combine coverage after the tests and generate the coverage report 
- Run the code-lint job before anything else
> Generate test coverage when running tests

- CHANGELOG
- setup.cfg
- setup.py
- Update test dependencies
- Update changelog
- Change next version to major update
> Update release candidate

- okonomiyaki/file_formats/tests/test__egg_info.py
- okonomiyaki/platforms/tests/test_python_implementation.py
- okonomiyaki/runtimes/tests/test_runtime_metadata.py
- okonomiyaki/versions/tests/test_enpkg_version.py
- okonomiyaki/versions/tests/test_semver.py
`assertRaisesRegexp()` is an [deprecated][1] alias that was removed in python 3.12. This replaces all instances with the new name, `assertRaisesRegex()`.
[1]: https://docs.python.org/3.11/library/unittest.html#deprecated-aliases
> Drop use of deprecated alias assertRaisesRegexp

- okonomiyaki/runtimes/tests/test_runtime.py
- okonomiyaki/utils/testing.py
fixes #471 
- Add a function to check if the current system is supported/compatible
- Skip `test_simple_from_running_python` on unsupported platforms
> Skip tests on unsupported platforms

- okonomiyaki/platforms/epd_platform.py
- okonomiyaki/platforms/tests/test_epd_platform.py
- Update applies function to work with long platform strings
- Update applies function to work with arm platform strings
- Rework and cleanup tests
> Fix arm support

- okonomiyaki/platforms/_arch.py
- okonomiyaki/platforms/tests/common.py
- okonomiyaki/platforms/tests/test__arch.py
- okonomiyaki/platforms/tests/test_platform.py
- On macos platform.machine will report x86_64 when the running python is executed through Rosetta. So we need to special case the code and workaround this behaviour
- mocks have been also updated to better mask the actual running system when running the tests
> Better detection of apple silicon arch
