enthought/okonomiyaki

okonomiyaki/platforms/epd_platform.py, okonomiyaki/platforms/platform.py, okonomiyaki/platforms/tests/common.py, okonomiyaki/platforms/tests/test_epd_platform.py
=> Fix osx kernel 32bits

okonomiyaki/platforms/epd_platform.py, okonomiyaki/platforms/tests/test_epd_platform.py
=> Allow new epd platform string

okonomiyaki/versions/pep386_workaround.py, okonomiyaki/versions/tests/test_pep386_workaround.py
@cournape Port enthought/enstaller_private#510 to okonomiyaki.
=> Remove last version string normalization hack

.coveragerc, tox.ini
=> ENH: use changedir to ensure we actually test the tarball.

okonomiyaki/platforms/tests/common.py, okonomiyaki/platforms/tests/test_epd_platform.py
Fix the test suite to run on windows properly
@sjagoe
=> Fix windows test

okonomiyaki/file_formats/__init__.py, okonomiyaki/file_formats/_package_info.py, okonomiyaki/file_formats/egg.py, okonomiyaki/file_formats/tests/test_egg_file_format.py, okonomiyaki/repositories/enpkg.py, okonomiyaki/repositories/grits.py
=> REF: make public API of okonomiyaki.file_formats clearer.

okonomiyaki/file_formats/egg.py, okonomiyaki/file_formats/tests/test_egg_file_format.py
Add a few lower-level methods to `EggBuilder`.
@sjagoe
=> FEAT: add_file and add_file_as methods.

okonomiyaki/file_formats/_egg_info.py, okonomiyaki/file_formats/tests/test_egg_file_format.py
This adds support for storing abi tag in `EGG-INFO/spec/depend` (with default values for `metadata_version < "1.3"`).
This is retrieved through the `abi_tag` attribute of `EggMetadata` instances.
@sjagoe
=> FEAT: add support for PEP425 abi tag.

setup.py
=> MAINT: use git describe for prettier dev numbers.

okonomiyaki/file_formats/_package_info.py, okonomiyaki/file_formats/tests/test__package_info.py, okonomiyaki/file_formats/tests/test_egg_file_format.py
=> BUG: reject unsupported metadata version in PKG-INFO.

CHANGELOG
Time to have a Changelog. I only list changes since `v0.7.0`
@sjagoe
=> MAINT: add Changelog.

CHANGELOG, okonomiyaki/__init__.py, setup.py
Will help okonomiyaki consumers to compare versions.
=> ENH: add okonomiyaki.__version_info__.

dev_requirements.txt, okonomiyaki/versions/enpkg.py, okonomiyaki/versions/tests/test_enpkg_version.py, okonomiyaki/versions/tests/test_pep386_workaround.py
=> Backport version from enstaller

CHANGELOG, okonomiyaki/bundled/traitlets/_implementation.py, okonomiyaki/bundled/traitlets/py3compat.py, okonomiyaki/file_formats/_egg_info.py, okonomiyaki/file_formats/_package_info.py, okonomiyaki/file_formats/setuptools_egg.py, okonomiyaki/file_formats/tests/test_egg_file_format.py, okonomiyaki/repositories/tests/test_enpkg.py, okonomiyaki/repositories/tests/test_grits.py, okonomiyaki/utils/__init__.py, okonomiyaki/utils/_compat.py, okonomiyaki/utils/misc.py, okonomiyaki/utils/py3compat.py, okonomiyaki/utils/tests/test_misc.py, okonomiyaki/versions/tests/test_enpkg_version.py, okonomiyaki/versions/tests/test_pep386_workaround.py, setup.py
This will make bundling in enstaller easier.
@sjagoe
=> Remove six dependency

okonomiyaki/platforms/epd_platform.py, okonomiyaki/platforms/tests/test_epd_platform.py
=> ENH: add support for '_'-separated epd strings.

CHANGELOG, okonomiyaki/platforms/epd_platform.py, okonomiyaki/platforms/tests/test_epd_platform.py
=> Handle eggs built for RedHat Enterprise 3

okonomiyaki/file_formats/tests/common.py, okonomiyaki/platforms/tests/test_epd_platform.py, setup.py
This fixes a broken test in EggRewriter on windows.
=> MAINT: update to latest zipfile2.

CHANGELOG, okonomiyaki/platforms/epd_platform.py, okonomiyaki/platforms/tests/test_epd_platform.py
=> Implement epd platform str

CHANGELOG
Forgot to add entry related to PR #134 in changelog
@sjagoe
=> MAINT: update changelog.

okonomiyaki/versions/pep386.py, okonomiyaki/versions/tests/test_pep386_workaround.py
=> BUG: fix string round tripping for versions with post and no dev part.

scripts/check_parse_existing_eggs.py
@cournape This adds a script that can generate and run metadata-parsing tests across a large set of eggs.
This catches all four of #86, #87, #88 and #89.
=> Add script to generate and run tests parsing all existing eggs

okonomiyaki/file_formats/_blacklist/__init__.py, okonomiyaki/file_formats/_blacklist/platform_tag.py
=> Update platform blacklist

okonomiyaki/file_formats/_egg_info.py, okonomiyaki/file_formats/tests/test__egg_info.py, okonomiyaki/versions/metadata_version.py, okonomiyaki/versions/tests/test_metadata_version.py
This will require a small change in brood when creating dummy egg
@sjagoe
=> Add metadata version

CHANGELOG
=> MAINT: update changelog following #146.

okonomiyaki/platforms/__init__.py, okonomiyaki/platforms/abi.py, okonomiyaki/platforms/platform.py, okonomiyaki/platforms/tests/test_abi.py, okonomiyaki/runtimes/runtime.py
=> ENH: update default_abi to work w/ implementations.

okonomiyaki/errors.py, okonomiyaki/file_formats/_egg_info.py, okonomiyaki/file_formats/tests/test__egg_info.py, okonomiyaki/platforms/python_implementation.py, okonomiyaki/platforms/tests/test_python_implementation.py, okonomiyaki/runtimes/runtime_metadata.py, okonomiyaki/runtimes/tests/test_runtime_metadata.py
=> Keep egg_name and requirement_string on relevant exception objects

okonomiyaki/runtimes/runtime_metadata.py, okonomiyaki/runtimes/tests/test_runtime_metadata.py, okonomiyaki/versions/metadata_version.py
=> BUG: fix bad error message for unsupported languages in runtime metadata

okonomiyaki/platforms/epd_platform.py, okonomiyaki/platforms/tests/test_epd_platform.py
=> BUG: fix broken codepath.

okonomiyaki/errors.py, okonomiyaki/versions/enpkg.py, okonomiyaki/versions/metadata_version.py, okonomiyaki/versions/pep440.py, okonomiyaki/versions/semver.py, okonomiyaki/versions/tests/test_enpkg_version.py, okonomiyaki/versions/tests/test_metadata_version.py, okonomiyaki/versions/tests/test_pep440.py, okonomiyaki/versions/tests/test_semver.py
@sjagoe, does that look reasonable for better error messages for invalid versions ?
=> ENH: raise okonomiyaki-specific errors in version classes for invalid version strings

scripts/check_parse_existing_eggs.py
=> Retry a download in test script if it fails due to bad sha256

okonomiyaki/platforms/epd_platform.py, okonomiyaki/platforms/tests/test_epd_platform.py
=> BUG: fix broken codepath in applies.

okonomiyaki/runtimes/runtime_metadata.py, okonomiyaki/runtimes/tests/test_runtime_metadata.py
@sjagoe is that what you had in mind for #166 ?
=> BUG: fix #166.

okonomiyaki/errors.py, okonomiyaki/file_formats/_egg_info.py, okonomiyaki/file_formats/tests/test__egg_info.py, okonomiyaki/platforms/tests/test_python_implementation.py
=> BUG: fix #156.

okonomiyaki/file_formats/_egg_info.py, okonomiyaki/utils/__init__.py, okonomiyaki/utils/py3compat.py
=> ENH: use text type instead of string where required.

CHANGELOG
=> MAINT: update Changelog for upcoming 0.15.0 release.

setup.py
=> DEP: Add enum34 dependency for python2.7

okonomiyaki/file_formats/_egg_info.py, okonomiyaki/file_formats/tests/test__egg_info.py
=> FEAT: move json serialization of EggMetadata from edm.

okonomiyaki/file_formats/_package_info.py, okonomiyaki/file_formats/tests/common.py, okonomiyaki/file_formats/tests/test__package_info.py
Some packages like setuptools 32.3.2 use this
=> FEAT: add support for PKG-INFO metadata 1.2.

README.rst, setup.py
Looks like README.rst is not handled automatically by pypi anymore.
=> MAINT: add (long) description into setup.py.

okonomiyaki/file_formats/_package_info.py, okonomiyaki/file_formats/_wheel_common.py, okonomiyaki/file_formats/_wheel_info.py, okonomiyaki/file_formats/tests/test__wheel_info.py
Add a new `WheelInfo` class that can parse pep 425 tags from a wheel filename.
=> FEAT: add WheelInfo class for wheel pep425 tags parsing.

README.rst
Add some basic examples in the `README`.
=> MAINT: add some basic examples in the README.

.travis.yml, appveyor.yml, okonomiyaki/runtimes/runtime.py, tox.ini
- Setup appveyor build to check issue #285 
- Setup python 3.6 build for Linux
fixes #285
=> Check support for python 3.6

.gitignore, .travis.yml, appveyor.yml, dev_requirements.txt, dev_requirements2.txt, okonomiyaki/platforms/_pep425_impl.py, okonomiyaki/platforms/pep425.py, okonomiyaki/runtimes/runtime.py, scripts/travis_install.sh, tox.ini
Backports:
- Merge pull request #284 from enthought/FIX/uspport-using-_run_pep425-… … 11bd8dd 
- Merge pull request #286 from enthought/maint/update-ci-setup … 68bf0e5 
- Merge pull request #288 from enthought/feat/support-python-3.6 … 81843fb
=> Backport recent fixes to 0.17.x

CHANGELOG
included PRs:
- Merge pull request #291 from enthought/maint-change-changelog-0.17.1 update changelog for 0.17.1 (cherry picked from commit 89acc03ecf225ec5ee9410a26a814d83e54c53b0)
=> Foward-port 0.17.1 change log

okonomiyaki/runtimes/tests/test_runtime.py
=> Update test to skip on known failure

okonomiyaki/file_formats/_wheel_info.py, okonomiyaki/file_formats/tests/test__wheel_info.py
This PR add attributes for the headers and scripts scheme in wheel_info
=> add attributes for the wheel headers and scripts scheme

okonomiyaki/file_formats/_wheel_info.py, okonomiyaki/file_formats/tests/test__wheel_info.py
=> backport recent fixes into wheel info.

appveyor.yml
Fixes https://github.com/enthought/okonomiyaki/issues/313
=> Don't use powershell for python/pip commands

okonomiyaki/file_formats/_egg_info.py, okonomiyaki/file_formats/_package_info.py, okonomiyaki/file_formats/legacy.py, okonomiyaki/file_formats/setuptools_egg.py, okonomiyaki/file_formats/tests/test_egg_file_format.py, okonomiyaki/platforms/epd_platform.py, okonomiyaki/platforms/platform_filters.py, okonomiyaki/platforms/python_implementation.py, okonomiyaki/versions/metadata_version.py, okonomiyaki/versions/semver.py, okonomiyaki/versions/tests/test_pep386_workaround.py, okonomiyaki/versions/tests/test_semver.py, setup.py
Fixes https://github.com/enthought/okonomiyaki/issues/315
=> Fix Travis CI errors

okonomiyaki/errors.py, okonomiyaki/file_formats/_egg_info.py, okonomiyaki/file_formats/tests/test__egg_info.py
Fixes https://github.com/enthought/okonomiyaki/issues/163
=> Improve error for hyphen in requirement string

CHANGELOG, setup.py
=> Update CHANGELOG for 1.0.0 release

setup.py
=> Add rh6 and rh7 egg folders to setup.py package_data

MANIFEST.in
=> Add license to manifest

okonomiyaki/platforms/_platform.py, okonomiyaki/platforms/tests/common.py, okonomiyaki/platforms/tests/test_epd_platform.py
=> Add centos 7.6 platform

.travis.yml
=> Allow maintenance and tagged branches to test with travis ci

okonomiyaki/runtimes/runtime_info.py, okonomiyaki/runtimes/tests/test_runtime_info.py, okonomiyaki/utils/misc.py, okonomiyaki/utils/tests/test_misc.py
=> Allow dollar signs in runtime_info prefix

jenkins/branch, jenkins/test
=> Add jenkins pr test pipeline

appveyor.yml
=> Only test branch builds for master and maintenance

setup.py
=> Add rh6 and rh7 dummy eggs to setup.py

jenkins/branch
=> Fix path to the jenkins okonomiyaki test build project

okonomiyaki/platforms/python_implementation.py, okonomiyaki/platforms/tests/test_python_implementation.py
- Support tags with more digits on the minor version
- Support tags with underscores
- Update and augment testing
=> Update python implementation

CHANGELOG, setup.py
- Update changlogs (including previous missing releases)
- Set release flag
=> Release 1.4.0

okonomiyaki/platforms/_platform.py, okonomiyaki/platforms/tests/test_platform.py, okonomiyaki/utils/misc.py, okonomiyaki/versions/pep440.py
=> Platform from dict

.github/workflows/test.yml, MANIFEST.in, README.rst, dev_requirements.txt, setup.cfg
- platforms: Dependencies for platforms and archs instances
- formats: Dependencies for files and archive instances
- all : All dependencies
=> Add optional dependencies into extras

.github/workflows/test.yml
=> Fix the github actions build
